apiVersion: v1
kind: Service
metadata:
  name: post-set-service
  namespace: k8s-program
  labels: 
    app: post-set
spec:
  type: NodePort
  selector:
    app: post-set
  ports:
    - port: 84
      targetPort: 8084
      nodePort: 30010
