apiVersion: v1
kind: Service
metadata:
  name: user-set-service
  namespace: k8s-program
  labels: 
    app: user-set
spec:
  type: NodePort
  selector:
    app: user-set
  ports:
    - port: 83
      targetPort: 8083
      nodePort: 30009

