apiVersion: v1
kind: Service
metadata:
  name: user-set-service
  namespace: k8s-program
  labels:
    database: user-set
spec:
  type: ClusterIP
  selector:
    database: user-set
  ports:
    - port: 83
      targetPort: 8083
