apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-set-database
  namespace: k8s-program
  labels:
    database: user-set
spec:
  selector:
    matchLabels:
      database: user-set
  serviceName: user-set
  replicas: 1
  template:
    metadata:
      labels:
        database: user-set
    spec:
      containers:
      - name: user-set-database
        image: postgres:latest
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: testuser
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_DB
            value: user
        volumeMounts:
          - mountPath: "/tmp"
            name: user-set-pvc
  volumeClaimTemplates:
    - metadata:
        name: user-set-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "hostpath"
        resources:
          requests:
            storage: 1Gi