apiVersion: v1
kind: Service
metadata:
  name: user-set-service-lb
  namespace: k8s-program
  labels: 
    app: user-set
spec:
  type: LoadBalancer
  selector:
    app: user-set
  ports:
    - port: 8083
      targetPort: 8083
