apiVersion: v1
kind: Service
metadata:
  name: user-service-lb
  namespace: k8s-program
  labels: 
    app: user
spec:
  type: LoadBalancer
  selector:
    app: user
  ports:
    - port: 8181
      targetPort: 8081
