apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  namespace: k8s-program
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-app
        image: djanigaepam/user-service:latest
        ports:
        - containerPort: 8081
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://user-database:5432/users
          - name: SPRING_DATASOURCE_USERNAME
            value: testuser
          - name: SPRING_DATASOURCE_PASSWORD
            value: password
          - name: SPRING_JPA_HIBERNATE_DDLAUTO
            value: create-drop
