apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-config
data:
  database: {{ .Values.database.name }}
  database_url: jdbc:postgresql://post-database:5432/posts
  user_service_url: http://user-service:81
  hibernate_create: update
  sql_show: "true"
  init.sql: |    
    CREATE TABLE posts (
      id        serial PRIMARY KEY,
      author_id INTEGER UNIQUE NOT NULL,
      text      VARCHAR(255)   NOT NULL,
      posted_at TIMESTAMP      NOT NULL
    );
    INSERT INTO posts (author_id, text, posted_at) VALUES (1, 'Initial post', '2022-05-26');
