apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-pv
  namespace: {{ .Values.namespace }}
  labels:
    type: local
spec:
  capacity: 
    storage: 1Gi
  storageClassName: manual
  hostPath:
    path: "/tmp"
  accessModes:
    - ReadWriteOnce
