apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "app.label" . }}
spec:
  type: ClusterIP
  selector:
    {{ include "app.label" . }}
  ports:
    - port: {{ .Values.container.port }}