apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}-database
  namespace: {{ .Values.namespace }}
  labels:
    database: {{ .Values.name }}-set
spec:
  selector:
    matchLabels:
      {{ include "database.label" . }}
  serviceName: {{ .Values.name }}-set
  replicas: {{ .Values.replicas.database }}
  template:
    metadata:
      labels:
        {{ include "database.label" . }}
    spec:
      containers:
      - name: {{ .Values.name }}-set-database
        image: postgres:latest
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.name }}-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.name }}-secret
                key: password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-config
                key: database
        volumeMounts:
          - mountPath: "/tmp"
            name: {{ .Values.name }}-set-pvc
          - mountPath: "/docker-entrypoint-initdb.d"
            name: init-script
        readinessProbe:
          exec:
            command: [ "psql", "-w", "-U", "testuser", "-d", "users", "-c", "SELECT 1" ]
          initialDelaySeconds: 15
          timeoutSeconds: 10
        livenessProbe:
          exec:
            command: [ "psql", "-w", "-U", "testuser", "-d", "users", "-c", "SELECT 1" ]
          initialDelaySeconds: 45
          timeoutSeconds: 10
        startupProbe:
          exec:
            command: [ "psql", "-w", "-U", "testuser", "-d", "users", "-c", "SELECT 1" ]
          initialDelaySeconds: 10
          timeoutSeconds: 10
      volumes:
        - name: init-script
          configMap:
            name: {{ .Values.name }}-config
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.name }}-set-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "hostpath"
        resources:
          requests:
            storage: 1Gi