apiVersion: v1
kind: PersistentVolume
metadata:
  name: post-pv
  namespace: k8s-program
  labels:
    type: local
spec:
  capacity: 
    storage: 1Gi
  storageClassName: manual
  hostPath:
    path: "/tmp"
  accessModes:
    - ReadWriteOnce
