apiVersion: v1
kind: Service
metadata:
  name: post-service-lb
  namespace: k8s-program
  labels: 
    app: post-set
spec:
  type: LoadBalancer
  selector:
    app: post-set
  ports:
    - port: 8082
      targetPort: 8082
