apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-app
  namespace: k8s-program
  labels:
    app: post
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post-app
        image: djanigaepam/post-service:2.0
        ports:
        - containerPort: 8082
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: post-config
                key: database_url
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: post-secret
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: post-secret
                key: password
          - name: USER_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: post-config
                key: user_service_url
          - name: SPRING_JPA_HIBERNATE_DDLAUTO
            valueFrom:
              configMapKeyRef:
                name: post-config
                key: hibernate_create
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 3
          failureThreshold: 30
          periodSeconds: 10
        volumeMounts:
        - mountPath: "/tmp"
          name: post-pv-storage
      volumes:
      - name: post-pv-storage
        persistentVolumeClaim:
          claimName: post-pvc
