apiVersion: v1
kind: Service
metadata:
  name: post-database
  namespace: k8s-program
  labels:
    database: post-set
spec:
  type: ClusterIP
  selector:
    database: post-set
  ports:
    - port: 5432